apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.13.0
metadata:
  name: 1.13-sample
apiServer:
  extraArgs:
    enable-admission-plugins: AlwaysPullImages,DefaultStorageClass
    token-auth-file: /etc/kubernetes/auth/tokens.csv
  extraVolumes:
  - name: tokens
    hostPath: /etc/kubernetes/auth
    mountPath: /etc/kubernetes/auth