apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: kuard
  name: kuard
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kuard
      version: "2"
  template:
    metadata:
      labels:
        app: kuard
        version: "2"
    spec:
      containers:
        - name: kuard
          image: "k8sschool/kuard-amd64:2"
